apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: thanos-receive
  name: thanos-receive
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thanos-receive
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        app: thanos-receive
    spec:
      containers:
      - args:
        - receive
        - --remote-write.address="0.0.0.0:19291"
        image: improbable/thanos:v0.5.0
        name: thanos-store
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 19291
          name: remote-write
  volumeClaimTemplates: []
