apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: thanos-store
  name: thanos-store
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thanos-store
  serviceName: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
      - args:
        - store
        - --data-dir=/var/thanos/store
        - --objstore.config=$(OBJSTORE_CONFIG)
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objectstorage
        image: improbable/thanos:v0.5.0-rc.0
        name: thanos-store
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        volumeMounts:
        - mountPath: /var/thanos/store
          name: data
          readOnly: false
      volumes:
      - emptyDir: {}
        name: data
  volumeClaimTemplates: []
