apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-store
  name: thanos-store
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  selector:
    app: thanos-store
